# Generated by Django 5.2.2 on 2025-09-23 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(default='', max_length=100)),
                ('prod_desc', models.CharField(default='', max_length=200)),
                ('prod_price', models.FloatField(default=0)),
                ('prod_quantity', models.IntegerField(default=0)),
            ],
        ),
    ]
