# Generated by Django 5.2.2 on 2025-09-23 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prod_image',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
