# Generated by Django 5.2.2 on 2025-09-23 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_product_prod_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prod_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
