# Generated by Django 5.2.2 on 2025-09-23 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_product_prod_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='prod_desc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='prod_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='prod_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='prod_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='prod_quantity',
            new_name='quantity',
        ),
    ]
