# Generated by Django 5.2.2 on 2025-09-23 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_rename_prod_desc_product_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(default='', max_length=10)),
                ('lastName', models.CharField(default='', max_length=10)),
                ('age', models.IntegerField(default=0)),
                ('address', models.TextField(default='', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='staff/')),
            ],
        ),
    ]
