# Generated by Django 5.2.2 on 2025-09-23 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='phoneNumber',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='staff',
            name='role',
            field=models.CharField(default='', max_length=20),
        ),
    ]
